2020-07-30 21:43:21> Program: Starting Squirrel Updater: --updateSelf=C:\Users\kevin\AppData\Local\SquirrelTemp\Update.exe
2020-07-30 21:43:21> Program: About to wait for parent PID 7208
2020-07-30 21:43:42> Unhandled exception: System.AggregateException: Um ou mais erros. ---> System.IO.IOException: O processo não pode acessar o arquivo 'C:\Users\kevin\AppData\Local\GitHubDesktop\app-2.5.3\..\Update.exe' porque ele está sendo usado por outro processo.
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   em System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   em Squirrel.Update.Program.<>c__DisplayClass6_0.<UpdateSelf>b__0()
   em System.Threading.Tasks.Task.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.Update.Program.<UpdateSelf>d__6.MoveNext()
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   em System.Threading.Tasks.Task.Wait()
   em Squirrel.Update.Program.executeCommandLine(String[] args)
   em Squirrel.Update.Program.main(String[] args)
---> (Exceção Interna N° 0) System.IO.IOException: O processo não pode acessar o arquivo 'C:\Users\kevin\AppData\Local\GitHubDesktop\app-2.5.3\..\Update.exe' porque ele está sendo usado por outro processo.
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   em System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   em Squirrel.Update.Program.<>c__DisplayClass6_0.<UpdateSelf>b__0()
   em System.Threading.Tasks.Task.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Squirrel.Update.Program.<UpdateSelf>d__6.MoveNext()<---

